#!/usr/bin/env python3
import requests
import json

cloudcidrs_url = "https://isc.sans.edu/api/cloudcidrs?json"
intelfeed_url = "https://isc.sans.edu/api/intelfeed?json"
user_agent = "isc-text-lists/1.0; +https://github.com/anon-123456789/isc-text-lists"
cloudcidrs_filename = "cloudcidrs.txt"
intelfeed_filename = "intelfeed.txt"
output_file_header = "# Generated by isc-text-lists (https://github.com/anon-123456789/isc-text-lists) from the Internet Storm Center API (https://isc.sans.edu/api/). Data licensed under CC BY-NC-SA 4.0."

def send_request(url):
    request_obj = requests.get(url, headers={"User-Agent": user_agent})

    # This will throw an error and exit if the response code isn't 200
    request_obj.raise_for_status()

    return request_obj


print(f"Fetching cloudcidrs from {cloudcidrs_url}")
cloudcidrs_request = send_request(cloudcidrs_url)

print(f"Fetching intelfeed from {intelfeed_url}")
intelfeed_request = send_request(intelfeed_url)


print("Converting cloudcidrs to dict")
cloudcidrs_json = cloudcidrs_request.json()

print("Converting intelfeed to dict")
intelfeed_json = intelfeed_request.json()


print("Extracting CIDRs from cloudcidrs")
cloudcidrs_data = [iterator["prefix"] for iterator in cloudcidrs_json]

print("Extracting IPs from intelfeed")
intelfeed_data = [iterator["ip"] for iterator in intelfeed_json]


print(f"cloudcidrs: {len(cloudcidrs_data)} CIDRs")
print(f"intelfeed: {len(intelfeed_data)} IPs")


print(f"Writing cloudcidrs with header to {cloudcidrs_filename}")
with open(cloudcidrs_filename, "w", encoding="utf-8") as cloudcidrs_file:
    cloudcidrs_file.write(output_file_header + "\n")
    cloudcidrs_file.write("\n".join(cloudcidrs_data))

print(f"Writing intelfeed with header to {intelfeed_filename}")
with open(intelfeed_filename, "w", encoding="utf-8") as intelfeed_file:
    intelfeed_file.write(output_file_header + "\n")
    intelfeed_file.write("\n".join(intelfeed_data))

print("\nDone!")