name: Build and Publish every 12 hours
run-name: Build list files and publish to GitHub Releases
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run build.py
        run: python3 build.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lists
          path: |
            cloudcidrs.txt
            intelfeed.txt
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: lists
      - name: Publish to GitHub Releases
        id: yet-another-upload-release-asset-action
        uses: shogo82148/actions-upload-release-asset@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/anon-123456789/isc-text-lists/releases/188228690/assets{?name,label}"
          asset_path: ./*.txt
          asset_content_type: text/plain
          overwrite: true