name: Build and Publish every 12 hours
run-name: Building list files and publish to GitHub Releases
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run build.py
        run: python3 build.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lists
          path: |
            cloudcidrs.txt
            intelfeed.txt
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: lists
      - name: Publish to GitHub Releases
        uses: IsaacShelton/update-existing-release@v1.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: "Latest List Files (ignore the date)"
          tag: "initial-commit"
          replace: true
          files: >
            cloudcidrs.txt
            intelfeed.txt